Repository InformedSolutions/JAQU-CAZ-MOD-UI, pull requests merged in 2020-05, with the labels that each got.

#89 Ignore yarn audit warning `1500`
  .drone.yml
Labels: bug

#90 [CAZB-1037] Update Data Rules page
  app/views/upload/data_rules.html.haml
Labels: documentation

#93 [CAZB-1037] Update Data Rules page
  app/views/upload/data_rules.html.haml
Labels: documentation

#94 [CAZB-1037] Update Data Rules page
  app/views/upload/data_rules.html.haml
Labels: documentation

#92 Promote Release/v1.1.0 to pre-production
  .drone.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/cookies_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/static_pages_controller.rb
  app/javascript/styles/cookie_control.scss
  app/services/cognito/auth_user.rb
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/rate_limit_verification.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/ses/send_success_email.rb
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_footer.html.haml
  app/views/layouts/application.html.haml
  app/views/static_pages/_cookie_control.html.haml
  app/views/static_pages/_ga.html.haml
  app/views/static_pages/_session.html.haml
  app/views/static_pages/_table_head.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.haml
  app/views/upload/data_rules.html.haml
  app/views/upload/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  config/routes.rb
  features/cookies.feature
  features/sign_in.feature
  features/static_pages.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/password_reset_steps.rb
  features/step_definitions/static_pages_steps.rb
  features/upload.feature
  lib/custom_logger.rb
  package.json
  public/robots.txt
  spec/requests/cookies_spec.rb
  spec/requests/passwords/change_spec.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/requests/static_pages_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  yarn.lock
Labels: release

#95 Promote v1.1.0 to Production
  .drone.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/cookies_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/static_pages_controller.rb
  app/javascript/styles/cookie_control.scss
  app/services/cognito/auth_user.rb
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/rate_limit_verification.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/ses/send_success_email.rb
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_footer.html.haml
  app/views/layouts/application.html.haml
  app/views/static_pages/_cookie_control.html.haml
  app/views/static_pages/_ga.html.haml
  app/views/static_pages/_session.html.haml
  app/views/static_pages/_table_head.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.haml
  app/views/upload/data_rules.html.haml
  app/views/upload/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  config/routes.rb
  features/cookies.feature
  features/sign_in.feature
  features/static_pages.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/password_reset_steps.rb
  features/step_definitions/static_pages_steps.rb
  features/upload.feature
  lib/custom_logger.rb
  package.json
  public/robots.txt
  spec/requests/cookies_spec.rb
  spec/requests/passwords/change_spec.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/requests/static_pages_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  yarn.lock
Labels: release, v1.1.0

#96 Promote release v1.1.1 to pre-production
  .drone.yml
  app/views/upload/data_rules.html.haml
Labels: release, v1.1.1

#97 Promote v1.1.1 to Production
  .drone.yml
  app/views/upload/data_rules.html.haml
Labels: release, v1.1.1

#99 [CAZB-1401] Do not log AWS SES response
  .drone.yml
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/ses/send_success_email.rb
  config/initializers/aws_custom_logger.rb
  config/initializers/aws_ses.rb
  config/initializers/new_framework_defaults.rb
Labels: bug
