Repository InformedSolutions/JAQU-CAZ-MOD-UI, pull requests merged in 2020-03, with the labels that each got.

#44 [NT] Update puma version to fix vulnerability warning
  Gemfile.lock
  package.json
  yarn.lock
Labels: documentation

#46 [CAZB-643] Content change to Cookie Policy
  .rubocop.yml
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/controllers/passwords_controller.rb
  app/helpers/application_helper.rb
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/_table_head.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/passwords/confirm_reset.html.haml
  app/views/passwords/reset.html.haml
  config/locales/en.yml
  features/cookies.feature
  yarn.lock
Labels: documentation

#47 [NT] Fix Cookie Control black button
  app/javascript/packs/application.js
  app/javascript/src/cookieControl.js
Labels: bug

#49 [NT] Ignore security warning for yarn audit
  .drone.yml
  package.json
  yarn.lock
Labels: bug

#51 [CAZB-893] Add secure cookies and CSP
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.haml
  config/initializers/content_security_policy.rb
  config/initializers/session_store.rb
  package.json
  yarn.lock
Labels: documentation

#52 [CAZB-885] Support case insensitive usernames
  app/services/email_validator.rb
Labels: documentation

#56 [CAZB-891] Add session hijacking prevention
  app/controllers/application_controller.rb
  app/models/user.rb
  app/services/cognito/auth_user.rb
  config/initializers/remote_authenticatable.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/upload_steps.rb
  features/support/login_helpers.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  spec/rails_helper.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/support/mock_user.rb
Labels: documentation

#57 [CAZB-892] Removal of row count from file naming convention
  app/api_wrappers/register_checker_api.rb
  app/services/csv_upload_service.rb
  app/views/upload/data_rules.html.haml
  features/step_definitions/upload_steps.rb
  spec/fixtures/files/csv/CAZ-2020-01-08.CSV
  spec/fixtures/files/csv/CAZ-2020-01-08.csv
  spec/fixtures/files/csv/empty/CAZ-2020-01-08-.csv
  spec/fixtures/files/csv/empty/CAZ-2020-01-08.xlsx
  spec/requests/upload_spec.rb
  spec/services/csv_upload_service_spec.rb
Labels: documentation

#62 Add mod ruby secret to drone pipeline
  .drone.yml
Labels: bug

#63 Promote drone file fixes for RC 1.0.0
  .drone.yml
Labels: bug, release
