Repository InformedSolutions/JAQU-CAZ-MOD-UI, pull requests merged in 2020-08, with the labels that each got.

#183 [CAZB-2333] Add configurable CSV size limit
  .env.example
  .env.test
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile.lock
  app/controllers/concerns/.keep
  app/controllers/passwords_controller.rb
  app/models/concerns/.keep
  app/services/csv_upload_service.rb
  config/application.rb
  config/initializers/amazon_s3.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/webpacker.rb
  config/puma.rb
  config/routes.rb
  features/step_definitions/upload_steps.rb
  features/upload.feature
  lib/assets/.keep
  lib/tasks/.keep
  package.json
  sonar-project.properties
  spec/services/csv_upload_service_spec.rb
  yarn.lock
Labels: documentation

#187 [CAZB-2748] Set Cache-control to no-store to prevent session reload
  config/environments/production.rb
Labels: bug

#207 [CAZB-2329] Update password policy
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/client.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/passwords/_errored_field.html.haml
  config/environments/production.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  features/force_password_change.feature
  features/password_reset.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/password_reset_steps.rb
  package.json
  yarn.lock
Labels: bug

#213 Promote 1.4.0 to staging
  .drone.yml
  .drone2.yml
  .env.example
  .github/dependabot.yml
  Gemfile.lock
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/models/new_password_form.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_gtm_noscript.html.erb
  app/views/layouts/_gtm_script.html.erb
  app/views/layouts/application.html.haml
  app/views/passwords/new.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  config/application.rb
  config/initializers/aws_custom_logger.rb
  config/initializers/content_security_policy.rb
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  features/password_reset.feature
  features/sign_in.feature
  features/step_definitions/force_password_change_steps.rb
  package-lock.json
  spec/models/new_password_form_spec.rb
  spec/requests/sign_in_spec.rb
  yarn.lock
Labels: release
