Repository InformedSolutions/JAQU-CAZ-MOD-UI, pull requests merged in 2021-02, with the labels that each got.

#304 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone.yml
  .drone2.yml
Labels: bug

#305 Promote release v1.8.1 to pre-production
  .drone.yml
  .drone2.yml
Labels: release, release/v1.8.1

#308 Promote MOD v1.8.1 to Production
  .drone.yml
  .drone2.yml
Labels: MOD v1.8.1, release
